---
# Configure DockbarX launcher
- name: install gconf2
  become: yes
  apt:
    name: gconf2
    state: present

- name: add launchers to dockbarx
  shell: |
    new_launcher='{{ item.1 }}'

    # Get the current list of launchers
    existing_launchers=$(gconftool-2 --get /apps/dockbarx/launchers 2> /dev/null \
      | grep --color=never '^\[' || echo "[]")

    # If the launcher is already in the list exit successfully here
    echo "$existing_launchers" | grep -P "[\[,]${new_launcher}[\],]" && { echo 'No changes' ; exit 0; }

    # Append the new launcher to the end of the list
    new_launchers=$(echo "$existing_launchers" | sed "s:\]$:,${new_launcher}\]:" | sed "s:^\[,:\[:")

    # Update the list of launchers
    gconftool-2 --type list --list-type=string \
      --set /apps/dockbarx/launchers "$new_launchers" \
    && { echo 'Changes applied' ; exit 1; } \
    || { echo 'Error' ; exit 2; }
  with_subelements:
    - "{{ users }}"
    - docbarx_launcher_items
  register: gconftool_result
  changed_when: 'gconftool_result.rc == 1'
  failed_when: 'gconftool_result.rc >= 2'
  become: yes
  become_user: "{{ item.0.username }}"
