---
- name: install libglib2.0-bin
  become: yes
  apt:
    name: libglib2.0-bin
    state: present

- name: write unity launcher config
  become: yes
  template:
    src: launcher.gschema.override.j2
    dest: "{{ pin_to_launcher_glib_schemas_directory }}/20_ansible_launcher.gschema.override"
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify:
    - compile glib schemas
